[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "crux"
version = "0.4"
description = "A summary-driven long-form RAG synthetic data generation pipeline."
authors = [{ name = "Dylan Ju", email = "j.ju@uva.nl" }]
dependencies = []

[tool.setuptools]
package-dir = {"" = "./"}

[tool.setuptools.packages.find]
where = ["./"]

# [tool.setuptools.package-data]
# reranking = ["configs/*.yaml"]

