---
tag: default-gen
model: meta-llama/Meta-Llama-3.1-8B-Instruct
model_tag: llama-3.1-8b
load_mode: vllm
batch_size: 1
temperature: 0.7
top_p: 0.95
max_new_tokens: 512
max_length: 8192
ampere_gpu: True
num_gpus: 1
